name: test
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile sample programs
      run: make
